// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transport

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/szymonpodeszwa/go-kvm-agent/pkg/api/transport"
)

// NewRoundTripperMock creates a new instance of RoundTripperMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoundTripperMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoundTripperMock {
	mock := &RoundTripperMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RoundTripperMock is an autogenerated mock type for the RoundTripper type
type RoundTripperMock struct {
	mock.Mock
}

type RoundTripperMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RoundTripperMock) EXPECT() *RoundTripperMock_Expecter {
	return &RoundTripperMock_Expecter{mock: &_m.Mock}
}

// Call provides a mock function for the type RoundTripperMock
func (_mock *RoundTripperMock) Call(ctx context.Context, request transport.Request) (*transport.Response, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *transport.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, transport.Request) (*transport.Response, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, transport.Request) *transport.Response); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transport.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, transport.Request) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoundTripperMock_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type RoundTripperMock_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - request transport.Request
func (_e *RoundTripperMock_Expecter) Call(ctx interface{}, request interface{}) *RoundTripperMock_Call_Call {
	return &RoundTripperMock_Call_Call{Call: _e.mock.On("Call", ctx, request)}
}

func (_c *RoundTripperMock_Call_Call) Run(run func(ctx context.Context, request transport.Request)) *RoundTripperMock_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 transport.Request
		if args[1] != nil {
			arg1 = args[1].(transport.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoundTripperMock_Call_Call) Return(response *transport.Response, err error) *RoundTripperMock_Call_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *RoundTripperMock_Call_Call) RunAndReturn(run func(ctx context.Context, request transport.Request) (*transport.Response, error)) *RoundTripperMock_Call_Call {
	_c.Call.Return(run)
	return _c
}
