name: local
local:
  peripherals:
    - driver: v4l2/display-source
      name: display-source
      config:
        devicePath: /dev/video0
        input:
          messageBoard:
            displayMode:
              width: 1920
              height: 1080
              refreshRate: 30
