// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package driver

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewDriverRepositoryMock creates a new instance of DriverRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDriverRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DriverRepositoryMock {
	mock := &DriverRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DriverRepositoryMock is an autogenerated mock type for the DriverRepository type
type DriverRepositoryMock struct {
	mock.Mock
}

type DriverRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DriverRepositoryMock) EXPECT() *DriverRepositoryMock_Expecter {
	return &DriverRepositoryMock_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type DriverRepositoryMock
func (_mock *DriverRepositoryMock) GetAll(ctx context.Context) ([]Driver, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []Driver
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]Driver, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Driver); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Driver)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DriverRepositoryMock_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type DriverRepositoryMock_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DriverRepositoryMock_Expecter) GetAll(ctx interface{}) *DriverRepositoryMock_GetAll_Call {
	return &DriverRepositoryMock_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *DriverRepositoryMock_GetAll_Call) Run(run func(ctx context.Context)) *DriverRepositoryMock_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DriverRepositoryMock_GetAll_Call) Return(drivers []Driver, err error) *DriverRepositoryMock_GetAll_Call {
	_c.Call.Return(drivers, err)
	return _c
}

func (_c *DriverRepositoryMock_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]Driver, error)) *DriverRepositoryMock_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByKind provides a mock function for the type DriverRepositoryMock
func (_mock *DriverRepositoryMock) GetByKind(ctx context.Context, kind Kind) (Driver, error) {
	ret := _mock.Called(ctx, kind)

	if len(ret) == 0 {
		panic("no return value specified for GetByKind")
	}

	var r0 Driver
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Kind) (Driver, error)); ok {
		return returnFunc(ctx, kind)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Kind) Driver); ok {
		r0 = returnFunc(ctx, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Driver)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Kind) error); ok {
		r1 = returnFunc(ctx, kind)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DriverRepositoryMock_GetByKind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKind'
type DriverRepositoryMock_GetByKind_Call struct {
	*mock.Call
}

// GetByKind is a helper method to define mock.On call
//   - ctx context.Context
//   - kind Kind
func (_e *DriverRepositoryMock_Expecter) GetByKind(ctx interface{}, kind interface{}) *DriverRepositoryMock_GetByKind_Call {
	return &DriverRepositoryMock_GetByKind_Call{Call: _e.mock.On("GetByKind", ctx, kind)}
}

func (_c *DriverRepositoryMock_GetByKind_Call) Run(run func(ctx context.Context, kind Kind)) *DriverRepositoryMock_GetByKind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Kind
		if args[1] != nil {
			arg1 = args[1].(Kind)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DriverRepositoryMock_GetByKind_Call) Return(driver Driver, err error) *DriverRepositoryMock_GetByKind_Call {
	_c.Call.Return(driver, err)
	return _c
}

func (_c *DriverRepositoryMock_GetByKind_Call) RunAndReturn(run func(ctx context.Context, kind Kind) (Driver, error)) *DriverRepositoryMock_GetByKind_Call {
	_c.Call.Return(run)
	return _c
}
