// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package driver

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/szymonpodeszwa/go-kvm-agent/pkg/peripheral"
)

// NewDriverMock creates a new instance of DriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DriverMock {
	mock := &DriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DriverMock is an autogenerated mock type for the Driver type
type DriverMock struct {
	mock.Mock
}

type DriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DriverMock) EXPECT() *DriverMock_Expecter {
	return &DriverMock_Expecter{mock: &_m.Mock}
}

// CreatePeripheral provides a mock function for the type DriverMock
func (_mock *DriverMock) CreatePeripheral(ctx context.Context, config any, name peripheral.Name) (peripheral.Peripheral, error) {
	ret := _mock.Called(ctx, config, name)

	if len(ret) == 0 {
		panic("no return value specified for CreatePeripheral")
	}

	var r0 peripheral.Peripheral
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, peripheral.Name) (peripheral.Peripheral, error)); ok {
		return returnFunc(ctx, config, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, peripheral.Name) peripheral.Peripheral); ok {
		r0 = returnFunc(ctx, config, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(peripheral.Peripheral)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any, peripheral.Name) error); ok {
		r1 = returnFunc(ctx, config, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DriverMock_CreatePeripheral_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePeripheral'
type DriverMock_CreatePeripheral_Call struct {
	*mock.Call
}

// CreatePeripheral is a helper method to define mock.On call
//   - ctx context.Context
//   - config any
//   - name peripheral.Name
func (_e *DriverMock_Expecter) CreatePeripheral(ctx interface{}, config interface{}, name interface{}) *DriverMock_CreatePeripheral_Call {
	return &DriverMock_CreatePeripheral_Call{Call: _e.mock.On("CreatePeripheral", ctx, config, name)}
}

func (_c *DriverMock_CreatePeripheral_Call) Run(run func(ctx context.Context, config any, name peripheral.Name)) *DriverMock_CreatePeripheral_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 peripheral.Name
		if args[2] != nil {
			arg2 = args[2].(peripheral.Name)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DriverMock_CreatePeripheral_Call) Return(peripheral1 peripheral.Peripheral, err error) *DriverMock_CreatePeripheral_Call {
	_c.Call.Return(peripheral1, err)
	return _c
}

func (_c *DriverMock_CreatePeripheral_Call) RunAndReturn(run func(ctx context.Context, config any, name peripheral.Name) (peripheral.Peripheral, error)) *DriverMock_CreatePeripheral_Call {
	_c.Call.Return(run)
	return _c
}

// GetKind provides a mock function for the type DriverMock
func (_mock *DriverMock) GetKind() Kind {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetKind")
	}

	var r0 Kind
	if returnFunc, ok := ret.Get(0).(func() Kind); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(Kind)
	}
	return r0
}

// DriverMock_GetKind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKind'
type DriverMock_GetKind_Call struct {
	*mock.Call
}

// GetKind is a helper method to define mock.On call
func (_e *DriverMock_Expecter) GetKind() *DriverMock_GetKind_Call {
	return &DriverMock_GetKind_Call{Call: _e.mock.On("GetKind")}
}

func (_c *DriverMock_GetKind_Call) Run(run func()) *DriverMock_GetKind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DriverMock_GetKind_Call) Return(kind Kind) *DriverMock_GetKind_Call {
	_c.Call.Return(kind)
	return _c
}

func (_c *DriverMock_GetKind_Call) RunAndReturn(run func() Kind) *DriverMock_GetKind_Call {
	_c.Call.Return(run)
	return _c
}
