// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package node

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewNodeMock creates a new instance of NodeMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeMock {
	mock := &NodeMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NodeMock is an autogenerated mock type for the Node type
type NodeMock struct {
	mock.Mock
}

type NodeMock_Expecter struct {
	mock *mock.Mock
}

func (_m *NodeMock) EXPECT() *NodeMock_Expecter {
	return &NodeMock_Expecter{mock: &_m.Mock}
}

// GetHostName provides a mock function for the type NodeMock
func (_mock *NodeMock) GetHostName(ctx context.Context) (*string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetHostName")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NodeMock_GetHostName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHostName'
type NodeMock_GetHostName_Call struct {
	*mock.Call
}

// GetHostName is a helper method to define mock.On call
//   - ctx context.Context
func (_e *NodeMock_Expecter) GetHostName(ctx interface{}) *NodeMock_GetHostName_Call {
	return &NodeMock_GetHostName_Call{Call: _e.mock.On("GetHostName", ctx)}
}

func (_c *NodeMock_GetHostName_Call) Run(run func(ctx context.Context)) *NodeMock_GetHostName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *NodeMock_GetHostName_Call) Return(hostName *string, err error) *NodeMock_GetHostName_Call {
	_c.Call.Return(hostName, err)
	return _c
}

func (_c *NodeMock_GetHostName_Call) RunAndReturn(run func(ctx context.Context) (*string, error)) *NodeMock_GetHostName_Call {
	_c.Call.Return(run)
	return _c
}

// GetLocalId provides a mock function for the type NodeMock
func (_mock *NodeMock) GetLocalId(ctx context.Context) (*NodeId, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetId")
	}

	var r0 *NodeId
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*NodeId, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *NodeId); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NodeId)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NodeMock_GetLocalId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type NodeMock_GetLocalId_Call struct {
	*mock.Call
}

// GetLocalId is a helper method to define mock.On call
//   - ctx context.Context
func (_e *NodeMock_Expecter) GetLocalId(ctx interface{}) *NodeMock_GetLocalId_Call {
	return &NodeMock_GetLocalId_Call{Call: _e.mock.On("GetId", ctx)}
}

func (_c *NodeMock_GetLocalId_Call) Run(run func(ctx context.Context)) *NodeMock_GetLocalId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *NodeMock_GetLocalId_Call) Return(nodeId *NodeId, err error) *NodeMock_GetLocalId_Call {
	_c.Call.Return(nodeId, err)
	return _c
}

func (_c *NodeMock_GetLocalId_Call) RunAndReturn(run func(ctx context.Context) (*NodeId, error)) *NodeMock_GetLocalId_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlatform provides a mock function for the type NodeMock
func (_mock *NodeMock) GetPlatform(ctx context.Context) (*NodePlatform, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPlatform")
	}

	var r0 *NodePlatform
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*NodePlatform, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *NodePlatform); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NodePlatform)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NodeMock_GetPlatform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlatform'
type NodeMock_GetPlatform_Call struct {
	*mock.Call
}

// GetPlatform is a helper method to define mock.On call
//   - ctx context.Context
func (_e *NodeMock_Expecter) GetPlatform(ctx interface{}) *NodeMock_GetPlatform_Call {
	return &NodeMock_GetPlatform_Call{Call: _e.mock.On("GetPlatform", ctx)}
}

func (_c *NodeMock_GetPlatform_Call) Run(run func(ctx context.Context)) *NodeMock_GetPlatform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *NodeMock_GetPlatform_Call) Return(platform *NodePlatform, err error) *NodeMock_GetPlatform_Call {
	_c.Call.Return(platform, err)
	return _c
}

func (_c *NodeMock_GetPlatform_Call) RunAndReturn(run func(ctx context.Context) (*NodePlatform, error)) *NodeMock_GetPlatform_Call {
	_c.Call.Return(run)
	return _c
}

// GetRole provides a mock function for the type NodeMock
func (_mock *NodeMock) GetRole(ctx context.Context) (*NodeRole, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 *NodeRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*NodeRole, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *NodeRole); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NodeRole)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NodeMock_GetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRole'
type NodeMock_GetRole_Call struct {
	*mock.Call
}

// GetRole is a helper method to define mock.On call
//   - ctx context.Context
func (_e *NodeMock_Expecter) GetRole(ctx interface{}) *NodeMock_GetRole_Call {
	return &NodeMock_GetRole_Call{Call: _e.mock.On("GetRole", ctx)}
}

func (_c *NodeMock_GetRole_Call) Run(run func(ctx context.Context)) *NodeMock_GetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *NodeMock_GetRole_Call) Return(nodeRole *NodeRole, err error) *NodeMock_GetRole_Call {
	_c.Call.Return(nodeRole, err)
	return _c
}

func (_c *NodeMock_GetRole_Call) RunAndReturn(run func(ctx context.Context) (*NodeRole, error)) *NodeMock_GetRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetUptime provides a mock function for the type NodeMock
func (_mock *NodeMock) GetUptime(ctx context.Context) (*time.Duration, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUptime")
	}

	var r0 *time.Duration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*time.Duration, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *time.Duration); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Duration)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NodeMock_GetUptime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUptime'
type NodeMock_GetUptime_Call struct {
	*mock.Call
}

// GetUptime is a helper method to define mock.On call
//   - ctx context.Context
func (_e *NodeMock_Expecter) GetUptime(ctx interface{}) *NodeMock_GetUptime_Call {
	return &NodeMock_GetUptime_Call{Call: _e.mock.On("GetUptime", ctx)}
}

func (_c *NodeMock_GetUptime_Call) Run(run func(ctx context.Context)) *NodeMock_GetUptime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *NodeMock_GetUptime_Call) Return(uptime *time.Duration, err error) *NodeMock_GetUptime_Call {
	_c.Call.Return(uptime, err)
	return _c
}

func (_c *NodeMock_GetUptime_Call) RunAndReturn(run func(ctx context.Context) (*time.Duration, error)) *NodeMock_GetUptime_Call {
	_c.Call.Return(run)
	return _c
}
