// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package node

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewNodeRepositoryMock creates a new instance of NodeRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeRepositoryMock {
	mock := &NodeRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NodeRepositoryMock is an autogenerated mock type for the NodeRepository type
type NodeRepositoryMock struct {
	mock.Mock
}

type NodeRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *NodeRepositoryMock) EXPECT() *NodeRepositoryMock_Expecter {
	return &NodeRepositoryMock_Expecter{mock: &_m.Mock}
}

// GetAllNodeIds provides a mock function for the type NodeRepositoryMock
func (_mock *NodeRepositoryMock) GetAllNodeIds(ctx context.Context) ([]NodeId, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllNodeIds")
	}

	var r0 []NodeId
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]NodeId, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []NodeId); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]NodeId)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NodeRepositoryMock_GetAllNodeIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllNodeIds'
type NodeRepositoryMock_GetAllNodeIds_Call struct {
	*mock.Call
}

// GetAllNodeIds is a helper method to define mock.On call
//   - ctx context.Context
func (_e *NodeRepositoryMock_Expecter) GetAllNodeIds(ctx interface{}) *NodeRepositoryMock_GetAllNodeIds_Call {
	return &NodeRepositoryMock_GetAllNodeIds_Call{Call: _e.mock.On("GetAllNodeIds", ctx)}
}

func (_c *NodeRepositoryMock_GetAllNodeIds_Call) Run(run func(ctx context.Context)) *NodeRepositoryMock_GetAllNodeIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *NodeRepositoryMock_GetAllNodeIds_Call) Return(nodeIds []NodeId, err error) *NodeRepositoryMock_GetAllNodeIds_Call {
	_c.Call.Return(nodeIds, err)
	return _c
}

func (_c *NodeRepositoryMock_GetAllNodeIds_Call) RunAndReturn(run func(ctx context.Context) ([]NodeId, error)) *NodeRepositoryMock_GetAllNodeIds_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeById provides a mock function for the type NodeRepositoryMock
func (_mock *NodeRepositoryMock) GetNodeById(ctx context.Context, nodeId NodeId) (Node, error) {
	ret := _mock.Called(ctx, nodeId)

	if len(ret) == 0 {
		panic("no return value specified for GetNodeById")
	}

	var r0 Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, NodeId) (Node, error)); ok {
		return returnFunc(ctx, nodeId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, NodeId) Node); ok {
		r0 = returnFunc(ctx, nodeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, NodeId) error); ok {
		r1 = returnFunc(ctx, nodeId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NodeRepositoryMock_GetNodeById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeById'
type NodeRepositoryMock_GetNodeById_Call struct {
	*mock.Call
}

// GetNodeById is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeId NodeId
func (_e *NodeRepositoryMock_Expecter) GetNodeById(ctx interface{}, nodeId interface{}) *NodeRepositoryMock_GetNodeById_Call {
	return &NodeRepositoryMock_GetNodeById_Call{Call: _e.mock.On("GetNodeById", ctx, nodeId)}
}

func (_c *NodeRepositoryMock_GetNodeById_Call) Run(run func(ctx context.Context, nodeId NodeId)) *NodeRepositoryMock_GetNodeById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 NodeId
		if args[1] != nil {
			arg1 = args[1].(NodeId)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NodeRepositoryMock_GetNodeById_Call) Return(node Node, err error) *NodeRepositoryMock_GetNodeById_Call {
	_c.Call.Return(node, err)
	return _c
}

func (_c *NodeRepositoryMock_GetNodeById_Call) RunAndReturn(run func(ctx context.Context, nodeId NodeId) (Node, error)) *NodeRepositoryMock_GetNodeById_Call {
	_c.Call.Return(run)
	return _c
}
