// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package node

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewServiceMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceMock is an autogenerated mock type for the Service type
type ServiceMock struct {
	mock.Mock
}

type ServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceMock) EXPECT() *ServiceMock_Expecter {
	return &ServiceMock_Expecter{mock: &_m.Mock}
}

// GetId provides a mock function for the type ServiceMock
func (_mock *ServiceMock) GetServiceId(ctx context.Context) (*ServiceId, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetId")
	}

	var r0 *ServiceId
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*ServiceId, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *ServiceId); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ServiceId)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type ServiceMock_GetId_Call struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ServiceMock_Expecter) GetId(ctx interface{}) *ServiceMock_GetId_Call {
	return &ServiceMock_GetId_Call{Call: _e.mock.On("GetId", ctx)}
}

func (_c *ServiceMock_GetId_Call) Run(run func(ctx context.Context)) *ServiceMock_GetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceMock_GetId_Call) Return(serviceId *ServiceId, err error) *ServiceMock_GetId_Call {
	_c.Call.Return(serviceId, err)
	return _c
}

func (_c *ServiceMock_GetId_Call) RunAndReturn(run func(ctx context.Context) (*ServiceId, error)) *ServiceMock_GetId_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function for the type ServiceMock
func (_mock *ServiceMock) Handle(stream io.ReadWriteCloser) {
	_mock.Called(stream)
	return
}

// ServiceMock_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type ServiceMock_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - stream io.ReadWriteCloser
func (_e *ServiceMock_Expecter) Handle(stream interface{}) *ServiceMock_Handle_Call {
	return &ServiceMock_Handle_Call{Call: _e.mock.On("Handle", stream)}
}

func (_c *ServiceMock_Handle_Call) Run(run func(stream io.ReadWriteCloser)) *ServiceMock_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.ReadWriteCloser
		if args[0] != nil {
			arg0 = args[0].(io.ReadWriteCloser)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceMock_Handle_Call) Return() *ServiceMock_Handle_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceMock_Handle_Call) RunAndReturn(run func(stream io.ReadWriteCloser)) *ServiceMock_Handle_Call {
	_c.Run(run)
	return _c
}
