// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package node

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewServiceRepositoryMock creates a new instance of ServiceRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceRepositoryMock {
	mock := &ServiceRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceRepositoryMock is an autogenerated mock type for the ServiceRepository type
type ServiceRepositoryMock struct {
	mock.Mock
}

type ServiceRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceRepositoryMock) EXPECT() *ServiceRepositoryMock_Expecter {
	return &ServiceRepositoryMock_Expecter{mock: &_m.Mock}
}

// GetAllServiceIds provides a mock function for the type ServiceRepositoryMock
func (_mock *ServiceRepositoryMock) GetAllServiceIds(ctx context.Context) ([]ServiceId, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllServiceIds")
	}

	var r0 []ServiceId
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ServiceId, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ServiceId); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ServiceId)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceRepositoryMock_GetAllServiceIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllServiceIds'
type ServiceRepositoryMock_GetAllServiceIds_Call struct {
	*mock.Call
}

// GetAllServiceIds is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ServiceRepositoryMock_Expecter) GetAllServiceIds(ctx interface{}) *ServiceRepositoryMock_GetAllServiceIds_Call {
	return &ServiceRepositoryMock_GetAllServiceIds_Call{Call: _e.mock.On("GetAllServiceIds", ctx)}
}

func (_c *ServiceRepositoryMock_GetAllServiceIds_Call) Run(run func(ctx context.Context)) *ServiceRepositoryMock_GetAllServiceIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceRepositoryMock_GetAllServiceIds_Call) Return(serviceIds []ServiceId, err error) *ServiceRepositoryMock_GetAllServiceIds_Call {
	_c.Call.Return(serviceIds, err)
	return _c
}

func (_c *ServiceRepositoryMock_GetAllServiceIds_Call) RunAndReturn(run func(ctx context.Context) ([]ServiceId, error)) *ServiceRepositoryMock_GetAllServiceIds_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceById provides a mock function for the type ServiceRepositoryMock
func (_mock *ServiceRepositoryMock) GetServiceById(ctx context.Context, serviceId ServiceId) (Service, error) {
	ret := _mock.Called(ctx, serviceId)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceById")
	}

	var r0 Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ServiceId) (Service, error)); ok {
		return returnFunc(ctx, serviceId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ServiceId) Service); ok {
		r0 = returnFunc(ctx, serviceId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ServiceId) error); ok {
		r1 = returnFunc(ctx, serviceId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceRepositoryMock_GetServiceById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceById'
type ServiceRepositoryMock_GetServiceById_Call struct {
	*mock.Call
}

// GetServiceById is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceId ServiceId
func (_e *ServiceRepositoryMock_Expecter) GetServiceById(ctx interface{}, serviceId interface{}) *ServiceRepositoryMock_GetServiceById_Call {
	return &ServiceRepositoryMock_GetServiceById_Call{Call: _e.mock.On("GetServiceById", ctx, serviceId)}
}

func (_c *ServiceRepositoryMock_GetServiceById_Call) Run(run func(ctx context.Context, serviceId ServiceId)) *ServiceRepositoryMock_GetServiceById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ServiceId
		if args[1] != nil {
			arg1 = args[1].(ServiceId)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceRepositoryMock_GetServiceById_Call) Return(service Service, err error) *ServiceRepositoryMock_GetServiceById_Call {
	_c.Call.Return(service, err)
	return _c
}

func (_c *ServiceRepositoryMock_GetServiceById_Call) RunAndReturn(run func(ctx context.Context, serviceId ServiceId) (Service, error)) *ServiceRepositoryMock_GetServiceById_Call {
	_c.Call.Return(run)
	return _c
}
