// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	mock "github.com/stretchr/testify/mock"
)

// NewCodecMock creates a new instance of CodecMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCodecMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CodecMock {
	mock := &CodecMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CodecMock is an autogenerated mock type for the Codec type
type CodecMock struct {
	mock.Mock
}

type CodecMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CodecMock) EXPECT() *CodecMock_Expecter {
	return &CodecMock_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function for the type CodecMock
func (_mock *CodecMock) Decode(value any) error {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CodecMock_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type CodecMock_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - value any
func (_e *CodecMock_Expecter) Decode(value interface{}) *CodecMock_Decode_Call {
	return &CodecMock_Decode_Call{Call: _e.mock.On("Decode", value)}
}

func (_c *CodecMock_Decode_Call) Run(run func(value any)) *CodecMock_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CodecMock_Decode_Call) Return(err error) *CodecMock_Decode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CodecMock_Decode_Call) RunAndReturn(run func(value any) error) *CodecMock_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Encode provides a mock function for the type CodecMock
func (_mock *CodecMock) Encode(value any) error {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CodecMock_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type CodecMock_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - value any
func (_e *CodecMock_Expecter) Encode(value interface{}) *CodecMock_Encode_Call {
	return &CodecMock_Encode_Call{Call: _e.mock.On("Encode", value)}
}

func (_c *CodecMock_Encode_Call) Run(run func(value any)) *CodecMock_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CodecMock_Encode_Call) Return(err error) *CodecMock_Encode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CodecMock_Encode_Call) RunAndReturn(run func(value any) error) *CodecMock_Encode_Call {
	_c.Call.Return(run)
	return _c
}
