// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
	"github.com/szymonpodeszwa/go-kvm-agent/pkg/node"
)

// NewTransportMock creates a new instance of TransportMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransportMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransportMock {
	mock := &TransportMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TransportMock is an autogenerated mock type for the Transport type
type TransportMock struct {
	mock.Mock
}

type TransportMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TransportMock) EXPECT() *TransportMock_Expecter {
	return &TransportMock_Expecter{mock: &_m.Mock}
}

// GetLocalNodeId provides a mock function for the type TransportMock
func (_mock *TransportMock) GetLocalNodeId() node.NodeId {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLocalNodeId")
	}

	var r0 node.NodeId
	if returnFunc, ok := ret.Get(0).(func() node.NodeId); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(node.NodeId)
	}
	return r0
}

// TransportMock_GetLocalNodeId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLocalNodeId'
type TransportMock_GetLocalNodeId_Call struct {
	*mock.Call
}

// GetLocalNodeId is a helper method to define mock.On call
func (_e *TransportMock_Expecter) GetLocalNodeId() *TransportMock_GetLocalNodeId_Call {
	return &TransportMock_GetLocalNodeId_Call{Call: _e.mock.On("GetLocalNodeId")}
}

func (_c *TransportMock_GetLocalNodeId_Call) Run(run func()) *TransportMock_GetLocalNodeId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TransportMock_GetLocalNodeId_Call) Return(nodeId node.NodeId) *TransportMock_GetLocalNodeId_Call {
	_c.Call.Return(nodeId)
	return _c
}

func (_c *TransportMock_GetLocalNodeId_Call) RunAndReturn(run func() node.NodeId) *TransportMock_GetLocalNodeId_Call {
	_c.Call.Return(run)
	return _c
}

// OpenServiceStream provides a mock function for the type TransportMock
func (_mock *TransportMock) OpenServiceStream(ctx context.Context, serviceId node.ServiceId, remoteNodeId node.NodeId) (io.ReadWriteCloser, error) {
	ret := _mock.Called(ctx, serviceId, remoteNodeId)

	if len(ret) == 0 {
		panic("no return value specified for OpenServiceStream")
	}

	var r0 io.ReadWriteCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, node.ServiceId, node.NodeId) (io.ReadWriteCloser, error)); ok {
		return returnFunc(ctx, serviceId, remoteNodeId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, node.ServiceId, node.NodeId) io.ReadWriteCloser); ok {
		r0 = returnFunc(ctx, serviceId, remoteNodeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadWriteCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, node.ServiceId, node.NodeId) error); ok {
		r1 = returnFunc(ctx, serviceId, remoteNodeId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransportMock_OpenServiceStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenServiceStream'
type TransportMock_OpenServiceStream_Call struct {
	*mock.Call
}

// OpenServiceStream is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceId node.ServiceId
//   - remoteNodeId node.NodeId
func (_e *TransportMock_Expecter) OpenServiceStream(ctx interface{}, serviceId interface{}, remoteNodeId interface{}) *TransportMock_OpenServiceStream_Call {
	return &TransportMock_OpenServiceStream_Call{Call: _e.mock.On("OpenServiceStream", ctx, serviceId, remoteNodeId)}
}

func (_c *TransportMock_OpenServiceStream_Call) Run(run func(ctx context.Context, serviceId node.ServiceId, remoteNodeId node.NodeId)) *TransportMock_OpenServiceStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 node.ServiceId
		if args[1] != nil {
			arg1 = args[1].(node.ServiceId)
		}
		var arg2 node.NodeId
		if args[2] != nil {
			arg2 = args[2].(node.NodeId)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TransportMock_OpenServiceStream_Call) Return(readWriteCloser io.ReadWriteCloser, err error) *TransportMock_OpenServiceStream_Call {
	_c.Call.Return(readWriteCloser, err)
	return _c
}

func (_c *TransportMock_OpenServiceStream_Call) RunAndReturn(run func(ctx context.Context, serviceId node.ServiceId, remoteNodeId node.NodeId) (io.ReadWriteCloser, error)) *TransportMock_OpenServiceStream_Call {
	_c.Call.Return(run)
	return _c
}

// Terminate provides a mock function for the type TransportMock
func (_mock *TransportMock) Terminate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Terminate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TransportMock_Terminate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Terminate'
type TransportMock_Terminate_Call struct {
	*mock.Call
}

// Terminate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TransportMock_Expecter) Terminate(ctx interface{}) *TransportMock_Terminate_Call {
	return &TransportMock_Terminate_Call{Call: _e.mock.On("Terminate", ctx)}
}

func (_c *TransportMock_Terminate_Call) Run(run func(ctx context.Context)) *TransportMock_Terminate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TransportMock_Terminate_Call) Return(err error) *TransportMock_Terminate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TransportMock_Terminate_Call) RunAndReturn(run func(ctx context.Context) error) *TransportMock_Terminate_Call {
	_c.Call.Return(run)
	return _c
}
