name: ffmpeg-display-sink
local:
  peripherals:
    - driver: ffmpeg/display-sink
      name: ffmpeg-display-sink
      config:
        title: "Hello World"
        supportedDisplayModes:
          - width: 800
            height: 600
            refreshRate: 30
