name: mpv-ffmpeg
peripherals:
  - driver: ffmpeg/display-source
    config:
      input:
        testPattern:
          displayMode:
            width: 800
            height: 600
            refreshRate: 30