name: ffmpeg-display-source
local:
  peripherals:
    - driver: ffmpeg/display-source
      name: ffmpeg-display-source
      config:
        input:
          messageBoard:
            displayMode:
              width: 800
              height: 600
              refreshRate: 30
