name: local
local:
  peripherals:
    - driver: ffmpeg/display-source
      name: display-source
      config:
        input:
          messageBoard:
            displayMode:
              width: 800
              height: 600
              refreshRate: 30
    - driver: ffmpeg/display-sink
      name: display-sink
      config:
        title: "Hello World"
        supportedDisplayModes:
          - width: 800
            height: 600
            refreshRate: 30
          - width: 1280
            height: 720
            refreshRate: 30
          - width: 1920
            height: 1080
            refreshRate: 30
