### Connect display sink to display source
POST http://127.0.0.1:8080/router/display/connect
Content-Type: application/json

{
  "displaySource": {
    "machineIdentifier": {
      "name": "ffmpeg-display-source"
    },
    "peripheralIdentifier": {
      "name": "ffmpeg-display-source"
    }
  },
  "displaySink": {
    "machineIdentifier": {
      "name": "ffmpeg-display-sink"
    },
    "peripheralIdentifier": {
      "name": "ffmpeg-display-sink"
    }
  }
}
