### Connect display sink to display source
POST http://{{ipAddress}}:8080/router/display/connect
Content-Type: application/json

{
  "displaySource": {
    "machineIdentifier": {
      "name": "remote"
    },
    "peripheralIdentifier": {
      "name": "display-source"
    }
  },
  "displaySink": {
    "machineIdentifier": {
      "name": "local"
    },
    "peripheralIdentifier": {
      "name": "display-sink"
    }
  }
}
