// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package peripheral

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewDisplaySinkMock creates a new instance of DisplaySinkMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDisplaySinkMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DisplaySinkMock {
	mock := &DisplaySinkMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DisplaySinkMock is an autogenerated mock type for the DisplaySink type
type DisplaySinkMock struct {
	mock.Mock
}

type DisplaySinkMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DisplaySinkMock) EXPECT() *DisplaySinkMock_Expecter {
	return &DisplaySinkMock_Expecter{mock: &_m.Mock}
}

// ClearDisplayFrameBufferProvider provides a mock function for the type DisplaySinkMock
func (_mock *DisplaySinkMock) ClearDisplayFrameBufferProvider() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClearDisplayFrameBufferProvider")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DisplaySinkMock_ClearDisplayFrameBufferProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearDisplayFrameBufferProvider'
type DisplaySinkMock_ClearDisplayFrameBufferProvider_Call struct {
	*mock.Call
}

// ClearDisplayFrameBufferProvider is a helper method to define mock.On call
func (_e *DisplaySinkMock_Expecter) ClearDisplayFrameBufferProvider() *DisplaySinkMock_ClearDisplayFrameBufferProvider_Call {
	return &DisplaySinkMock_ClearDisplayFrameBufferProvider_Call{Call: _e.mock.On("ClearDisplayFrameBufferProvider")}
}

func (_c *DisplaySinkMock_ClearDisplayFrameBufferProvider_Call) Run(run func()) *DisplaySinkMock_ClearDisplayFrameBufferProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DisplaySinkMock_ClearDisplayFrameBufferProvider_Call) Return(err error) *DisplaySinkMock_ClearDisplayFrameBufferProvider_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DisplaySinkMock_ClearDisplayFrameBufferProvider_Call) RunAndReturn(run func() error) *DisplaySinkMock_ClearDisplayFrameBufferProvider_Call {
	_c.Call.Return(run)
	return _c
}

// GetCapabilities provides a mock function for the type DisplaySinkMock
func (_mock *DisplaySinkMock) GetCapabilities() []PeripheralCapability {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCapabilities")
	}

	var r0 []PeripheralCapability
	if returnFunc, ok := ret.Get(0).(func() []PeripheralCapability); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PeripheralCapability)
		}
	}
	return r0
}

// DisplaySinkMock_GetCapabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCapabilities'
type DisplaySinkMock_GetCapabilities_Call struct {
	*mock.Call
}

// GetCapabilities is a helper method to define mock.On call
func (_e *DisplaySinkMock_Expecter) GetCapabilities() *DisplaySinkMock_GetCapabilities_Call {
	return &DisplaySinkMock_GetCapabilities_Call{Call: _e.mock.On("GetCapabilities")}
}

func (_c *DisplaySinkMock_GetCapabilities_Call) Run(run func()) *DisplaySinkMock_GetCapabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DisplaySinkMock_GetCapabilities_Call) Return(peripheralCapabilitys []PeripheralCapability) *DisplaySinkMock_GetCapabilities_Call {
	_c.Call.Return(peripheralCapabilitys)
	return _c
}

func (_c *DisplaySinkMock_GetCapabilities_Call) RunAndReturn(run func() []PeripheralCapability) *DisplaySinkMock_GetCapabilities_Call {
	_c.Call.Return(run)
	return _c
}

// GetId provides a mock function for the type DisplaySinkMock
func (_mock *DisplaySinkMock) GetId() PeripheralId {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetId")
	}

	var r0 PeripheralId
	if returnFunc, ok := ret.Get(0).(func() PeripheralId); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(PeripheralId)
	}
	return r0
}

// DisplaySinkMock_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type DisplaySinkMock_GetId_Call struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
func (_e *DisplaySinkMock_Expecter) GetId() *DisplaySinkMock_GetId_Call {
	return &DisplaySinkMock_GetId_Call{Call: _e.mock.On("GetId")}
}

func (_c *DisplaySinkMock_GetId_Call) Run(run func()) *DisplaySinkMock_GetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DisplaySinkMock_GetId_Call) Return(peripheralId PeripheralId) *DisplaySinkMock_GetId_Call {
	_c.Call.Return(peripheralId)
	return _c
}

func (_c *DisplaySinkMock_GetId_Call) RunAndReturn(run func() PeripheralId) *DisplaySinkMock_GetId_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type DisplaySinkMock
func (_mock *DisplaySinkMock) GetName() PeripheralName {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 PeripheralName
	if returnFunc, ok := ret.Get(0).(func() PeripheralName); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(PeripheralName)
	}
	return r0
}

// DisplaySinkMock_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type DisplaySinkMock_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *DisplaySinkMock_Expecter) GetName() *DisplaySinkMock_GetName_Call {
	return &DisplaySinkMock_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *DisplaySinkMock_GetName_Call) Run(run func()) *DisplaySinkMock_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DisplaySinkMock_GetName_Call) Return(peripheralName PeripheralName) *DisplaySinkMock_GetName_Call {
	_c.Call.Return(peripheralName)
	return _c
}

func (_c *DisplaySinkMock_GetName_Call) RunAndReturn(run func() PeripheralName) *DisplaySinkMock_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// SetDisplayFrameBufferProvider provides a mock function for the type DisplaySinkMock
func (_mock *DisplaySinkMock) SetDisplayFrameBufferProvider(provider DisplayFrameBufferProvider) error {
	ret := _mock.Called(provider)

	if len(ret) == 0 {
		panic("no return value specified for SetDisplayFrameBufferProvider")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(DisplayFrameBufferProvider) error); ok {
		r0 = returnFunc(provider)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DisplaySinkMock_SetDisplayFrameBufferProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDisplayFrameBufferProvider'
type DisplaySinkMock_SetDisplayFrameBufferProvider_Call struct {
	*mock.Call
}

// SetDisplayFrameBufferProvider is a helper method to define mock.On call
//   - provider DisplayFrameBufferProvider
func (_e *DisplaySinkMock_Expecter) SetDisplayFrameBufferProvider(provider interface{}) *DisplaySinkMock_SetDisplayFrameBufferProvider_Call {
	return &DisplaySinkMock_SetDisplayFrameBufferProvider_Call{Call: _e.mock.On("SetDisplayFrameBufferProvider", provider)}
}

func (_c *DisplaySinkMock_SetDisplayFrameBufferProvider_Call) Run(run func(provider DisplayFrameBufferProvider)) *DisplaySinkMock_SetDisplayFrameBufferProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 DisplayFrameBufferProvider
		if args[0] != nil {
			arg0 = args[0].(DisplayFrameBufferProvider)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DisplaySinkMock_SetDisplayFrameBufferProvider_Call) Return(err error) *DisplaySinkMock_SetDisplayFrameBufferProvider_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DisplaySinkMock_SetDisplayFrameBufferProvider_Call) RunAndReturn(run func(provider DisplayFrameBufferProvider) error) *DisplaySinkMock_SetDisplayFrameBufferProvider_Call {
	_c.Call.Return(run)
	return _c
}

// Terminate provides a mock function for the type DisplaySinkMock
func (_mock *DisplaySinkMock) Terminate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Terminate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DisplaySinkMock_Terminate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Terminate'
type DisplaySinkMock_Terminate_Call struct {
	*mock.Call
}

// Terminate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DisplaySinkMock_Expecter) Terminate(ctx interface{}) *DisplaySinkMock_Terminate_Call {
	return &DisplaySinkMock_Terminate_Call{Call: _e.mock.On("Terminate", ctx)}
}

func (_c *DisplaySinkMock_Terminate_Call) Run(run func(ctx context.Context)) *DisplaySinkMock_Terminate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DisplaySinkMock_Terminate_Call) Return(err error) *DisplaySinkMock_Terminate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DisplaySinkMock_Terminate_Call) RunAndReturn(run func(ctx context.Context) error) *DisplaySinkMock_Terminate_Call {
	_c.Call.Return(run)
	return _c
}
