// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package peripheral

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewKeyboardSinkMock creates a new instance of KeyboardSinkMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyboardSinkMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyboardSinkMock {
	mock := &KeyboardSinkMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KeyboardSinkMock is an autogenerated mock type for the KeyboardSink type
type KeyboardSinkMock struct {
	mock.Mock
}

type KeyboardSinkMock_Expecter struct {
	mock *mock.Mock
}

func (_m *KeyboardSinkMock) EXPECT() *KeyboardSinkMock_Expecter {
	return &KeyboardSinkMock_Expecter{mock: &_m.Mock}
}

// GetCapabilities provides a mock function for the type KeyboardSinkMock
func (_mock *KeyboardSinkMock) GetCapabilities() []PeripheralCapability {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCapabilities")
	}

	var r0 []PeripheralCapability
	if returnFunc, ok := ret.Get(0).(func() []PeripheralCapability); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PeripheralCapability)
		}
	}
	return r0
}

// KeyboardSinkMock_GetCapabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCapabilities'
type KeyboardSinkMock_GetCapabilities_Call struct {
	*mock.Call
}

// GetCapabilities is a helper method to define mock.On call
func (_e *KeyboardSinkMock_Expecter) GetCapabilities() *KeyboardSinkMock_GetCapabilities_Call {
	return &KeyboardSinkMock_GetCapabilities_Call{Call: _e.mock.On("GetCapabilities")}
}

func (_c *KeyboardSinkMock_GetCapabilities_Call) Run(run func()) *KeyboardSinkMock_GetCapabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KeyboardSinkMock_GetCapabilities_Call) Return(peripheralCapabilitys []PeripheralCapability) *KeyboardSinkMock_GetCapabilities_Call {
	_c.Call.Return(peripheralCapabilitys)
	return _c
}

func (_c *KeyboardSinkMock_GetCapabilities_Call) RunAndReturn(run func() []PeripheralCapability) *KeyboardSinkMock_GetCapabilities_Call {
	_c.Call.Return(run)
	return _c
}

// GetId provides a mock function for the type KeyboardSinkMock
func (_mock *KeyboardSinkMock) GetId() PeripheralId {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetId")
	}

	var r0 PeripheralId
	if returnFunc, ok := ret.Get(0).(func() PeripheralId); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(PeripheralId)
	}
	return r0
}

// KeyboardSinkMock_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type KeyboardSinkMock_GetId_Call struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
func (_e *KeyboardSinkMock_Expecter) GetId() *KeyboardSinkMock_GetId_Call {
	return &KeyboardSinkMock_GetId_Call{Call: _e.mock.On("GetId")}
}

func (_c *KeyboardSinkMock_GetId_Call) Run(run func()) *KeyboardSinkMock_GetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KeyboardSinkMock_GetId_Call) Return(peripheralId PeripheralId) *KeyboardSinkMock_GetId_Call {
	_c.Call.Return(peripheralId)
	return _c
}

func (_c *KeyboardSinkMock_GetId_Call) RunAndReturn(run func() PeripheralId) *KeyboardSinkMock_GetId_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type KeyboardSinkMock
func (_mock *KeyboardSinkMock) GetName() PeripheralName {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 PeripheralName
	if returnFunc, ok := ret.Get(0).(func() PeripheralName); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(PeripheralName)
	}
	return r0
}

// KeyboardSinkMock_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type KeyboardSinkMock_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *KeyboardSinkMock_Expecter) GetName() *KeyboardSinkMock_GetName_Call {
	return &KeyboardSinkMock_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *KeyboardSinkMock_GetName_Call) Run(run func()) *KeyboardSinkMock_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KeyboardSinkMock_GetName_Call) Return(peripheralName PeripheralName) *KeyboardSinkMock_GetName_Call {
	_c.Call.Return(peripheralName)
	return _c
}

func (_c *KeyboardSinkMock_GetName_Call) RunAndReturn(run func() PeripheralName) *KeyboardSinkMock_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// HandleKeyboardDataEvent provides a mock function for the type KeyboardSinkMock
func (_mock *KeyboardSinkMock) HandleKeyboardDataEvent(event KeyboardEvent) error {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for HandleKeyboardDataEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(KeyboardEvent) error); ok {
		r0 = returnFunc(event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KeyboardSinkMock_HandleKeyboardDataEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleKeyboardDataEvent'
type KeyboardSinkMock_HandleKeyboardDataEvent_Call struct {
	*mock.Call
}

// HandleKeyboardDataEvent is a helper method to define mock.On call
//   - event KeyboardEvent
func (_e *KeyboardSinkMock_Expecter) HandleKeyboardDataEvent(event interface{}) *KeyboardSinkMock_HandleKeyboardDataEvent_Call {
	return &KeyboardSinkMock_HandleKeyboardDataEvent_Call{Call: _e.mock.On("HandleKeyboardDataEvent", event)}
}

func (_c *KeyboardSinkMock_HandleKeyboardDataEvent_Call) Run(run func(event KeyboardEvent)) *KeyboardSinkMock_HandleKeyboardDataEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 KeyboardEvent
		if args[0] != nil {
			arg0 = args[0].(KeyboardEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *KeyboardSinkMock_HandleKeyboardDataEvent_Call) Return(err error) *KeyboardSinkMock_HandleKeyboardDataEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KeyboardSinkMock_HandleKeyboardDataEvent_Call) RunAndReturn(run func(event KeyboardEvent) error) *KeyboardSinkMock_HandleKeyboardDataEvent_Call {
	_c.Call.Return(run)
	return _c
}

// KeyboardControlChannel provides a mock function for the type KeyboardSinkMock
func (_mock *KeyboardSinkMock) KeyboardControlChannel(ctx context.Context) <-chan KeyboardControlEvent {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for KeyboardControlChannel")
	}

	var r0 <-chan KeyboardControlEvent
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan KeyboardControlEvent); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan KeyboardControlEvent)
		}
	}
	return r0
}

// KeyboardSinkMock_KeyboardControlChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeyboardControlChannel'
type KeyboardSinkMock_KeyboardControlChannel_Call struct {
	*mock.Call
}

// KeyboardControlChannel is a helper method to define mock.On call
//   - ctx context.Context
func (_e *KeyboardSinkMock_Expecter) KeyboardControlChannel(ctx interface{}) *KeyboardSinkMock_KeyboardControlChannel_Call {
	return &KeyboardSinkMock_KeyboardControlChannel_Call{Call: _e.mock.On("KeyboardControlChannel", ctx)}
}

func (_c *KeyboardSinkMock_KeyboardControlChannel_Call) Run(run func(ctx context.Context)) *KeyboardSinkMock_KeyboardControlChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *KeyboardSinkMock_KeyboardControlChannel_Call) Return(keyboardControlEventCh <-chan KeyboardControlEvent) *KeyboardSinkMock_KeyboardControlChannel_Call {
	_c.Call.Return(keyboardControlEventCh)
	return _c
}

func (_c *KeyboardSinkMock_KeyboardControlChannel_Call) RunAndReturn(run func(ctx context.Context) <-chan KeyboardControlEvent) *KeyboardSinkMock_KeyboardControlChannel_Call {
	_c.Call.Return(run)
	return _c
}

// Terminate provides a mock function for the type KeyboardSinkMock
func (_mock *KeyboardSinkMock) Terminate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Terminate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KeyboardSinkMock_Terminate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Terminate'
type KeyboardSinkMock_Terminate_Call struct {
	*mock.Call
}

// Terminate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *KeyboardSinkMock_Expecter) Terminate(ctx interface{}) *KeyboardSinkMock_Terminate_Call {
	return &KeyboardSinkMock_Terminate_Call{Call: _e.mock.On("Terminate", ctx)}
}

func (_c *KeyboardSinkMock_Terminate_Call) Run(run func(ctx context.Context)) *KeyboardSinkMock_Terminate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *KeyboardSinkMock_Terminate_Call) Return(err error) *KeyboardSinkMock_Terminate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KeyboardSinkMock_Terminate_Call) RunAndReturn(run func(ctx context.Context) error) *KeyboardSinkMock_Terminate_Call {
	_c.Call.Return(run)
	return _c
}
