// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package peripheral

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMouseSinkMock creates a new instance of MouseSinkMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMouseSinkMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MouseSinkMock {
	mock := &MouseSinkMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MouseSinkMock is an autogenerated mock type for the MouseSink type
type MouseSinkMock struct {
	mock.Mock
}

type MouseSinkMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MouseSinkMock) EXPECT() *MouseSinkMock_Expecter {
	return &MouseSinkMock_Expecter{mock: &_m.Mock}
}

// Capabilities provides a mock function for the type MouseSinkMock
func (_mock *MouseSinkMock) Capabilities() []PeripheralCapability {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Capabilities")
	}

	var r0 []PeripheralCapability
	if returnFunc, ok := ret.Get(0).(func() []PeripheralCapability); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PeripheralCapability)
		}
	}
	return r0
}

// MouseSinkMock_Capabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capabilities'
type MouseSinkMock_Capabilities_Call struct {
	*mock.Call
}

// Capabilities is a helper method to define mock.On call
func (_e *MouseSinkMock_Expecter) Capabilities() *MouseSinkMock_Capabilities_Call {
	return &MouseSinkMock_Capabilities_Call{Call: _e.mock.On("Capabilities")}
}

func (_c *MouseSinkMock_Capabilities_Call) Run(run func()) *MouseSinkMock_Capabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MouseSinkMock_Capabilities_Call) Return(peripheralCapabilitys []PeripheralCapability) *MouseSinkMock_Capabilities_Call {
	_c.Call.Return(peripheralCapabilitys)
	return _c
}

func (_c *MouseSinkMock_Capabilities_Call) RunAndReturn(run func() []PeripheralCapability) *MouseSinkMock_Capabilities_Call {
	_c.Call.Return(run)
	return _c
}

// Id provides a mock function for the type MouseSinkMock
func (_mock *MouseSinkMock) Id() PeripheralId {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Id")
	}

	var r0 PeripheralId
	if returnFunc, ok := ret.Get(0).(func() PeripheralId); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(PeripheralId)
	}
	return r0
}

// MouseSinkMock_Id_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Id'
type MouseSinkMock_Id_Call struct {
	*mock.Call
}

// Id is a helper method to define mock.On call
func (_e *MouseSinkMock_Expecter) Id() *MouseSinkMock_Id_Call {
	return &MouseSinkMock_Id_Call{Call: _e.mock.On("Id")}
}

func (_c *MouseSinkMock_Id_Call) Run(run func()) *MouseSinkMock_Id_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MouseSinkMock_Id_Call) Return(peripheralId PeripheralId) *MouseSinkMock_Id_Call {
	_c.Call.Return(peripheralId)
	return _c
}

func (_c *MouseSinkMock_Id_Call) RunAndReturn(run func() PeripheralId) *MouseSinkMock_Id_Call {
	_c.Call.Return(run)
	return _c
}

// Terminate provides a mock function for the type MouseSinkMock
func (_mock *MouseSinkMock) Terminate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Terminate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MouseSinkMock_Terminate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Terminate'
type MouseSinkMock_Terminate_Call struct {
	*mock.Call
}

// Terminate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MouseSinkMock_Expecter) Terminate(ctx interface{}) *MouseSinkMock_Terminate_Call {
	return &MouseSinkMock_Terminate_Call{Call: _e.mock.On("Terminate", ctx)}
}

func (_c *MouseSinkMock_Terminate_Call) Run(run func(ctx context.Context)) *MouseSinkMock_Terminate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MouseSinkMock_Terminate_Call) Return(err error) *MouseSinkMock_Terminate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MouseSinkMock_Terminate_Call) RunAndReturn(run func(ctx context.Context) error) *MouseSinkMock_Terminate_Call {
	_c.Call.Return(run)
	return _c
}
