// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package peripheral

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMouseSourceMock creates a new instance of MouseSourceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMouseSourceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MouseSourceMock {
	mock := &MouseSourceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MouseSourceMock is an autogenerated mock type for the MouseSource type
type MouseSourceMock struct {
	mock.Mock
}

type MouseSourceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MouseSourceMock) EXPECT() *MouseSourceMock_Expecter {
	return &MouseSourceMock_Expecter{mock: &_m.Mock}
}

// GetCapabilities provides a mock function for the type MouseSourceMock
func (_mock *MouseSourceMock) GetCapabilities() []PeripheralCapability {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCapabilities")
	}

	var r0 []PeripheralCapability
	if returnFunc, ok := ret.Get(0).(func() []PeripheralCapability); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PeripheralCapability)
		}
	}
	return r0
}

// MouseSourceMock_GetCapabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCapabilities'
type MouseSourceMock_GetCapabilities_Call struct {
	*mock.Call
}

// GetCapabilities is a helper method to define mock.On call
func (_e *MouseSourceMock_Expecter) GetCapabilities() *MouseSourceMock_GetCapabilities_Call {
	return &MouseSourceMock_GetCapabilities_Call{Call: _e.mock.On("GetCapabilities")}
}

func (_c *MouseSourceMock_GetCapabilities_Call) Run(run func()) *MouseSourceMock_GetCapabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MouseSourceMock_GetCapabilities_Call) Return(peripheralCapabilitys []PeripheralCapability) *MouseSourceMock_GetCapabilities_Call {
	_c.Call.Return(peripheralCapabilitys)
	return _c
}

func (_c *MouseSourceMock_GetCapabilities_Call) RunAndReturn(run func() []PeripheralCapability) *MouseSourceMock_GetCapabilities_Call {
	_c.Call.Return(run)
	return _c
}

// GetId provides a mock function for the type MouseSourceMock
func (_mock *MouseSourceMock) GetId() Id {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetId")
	}

	var r0 Id
	if returnFunc, ok := ret.Get(0).(func() Id); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(Id)
	}
	return r0
}

// MouseSourceMock_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type MouseSourceMock_GetId_Call struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
func (_e *MouseSourceMock_Expecter) GetId() *MouseSourceMock_GetId_Call {
	return &MouseSourceMock_GetId_Call{Call: _e.mock.On("GetId")}
}

func (_c *MouseSourceMock_GetId_Call) Run(run func()) *MouseSourceMock_GetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MouseSourceMock_GetId_Call) Return(id Id) *MouseSourceMock_GetId_Call {
	_c.Call.Return(id)
	return _c
}

func (_c *MouseSourceMock_GetId_Call) RunAndReturn(run func() Id) *MouseSourceMock_GetId_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MouseSourceMock
func (_mock *MouseSourceMock) GetName() Name {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 Name
	if returnFunc, ok := ret.Get(0).(func() Name); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(Name)
	}
	return r0
}

// MouseSourceMock_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MouseSourceMock_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MouseSourceMock_Expecter) GetName() *MouseSourceMock_GetName_Call {
	return &MouseSourceMock_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MouseSourceMock_GetName_Call) Run(run func()) *MouseSourceMock_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MouseSourceMock_GetName_Call) Return(name Name) *MouseSourceMock_GetName_Call {
	_c.Call.Return(name)
	return _c
}

func (_c *MouseSourceMock_GetName_Call) RunAndReturn(run func() Name) *MouseSourceMock_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// Terminate provides a mock function for the type MouseSourceMock
func (_mock *MouseSourceMock) Terminate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Terminate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MouseSourceMock_Terminate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Terminate'
type MouseSourceMock_Terminate_Call struct {
	*mock.Call
}

// Terminate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MouseSourceMock_Expecter) Terminate(ctx interface{}) *MouseSourceMock_Terminate_Call {
	return &MouseSourceMock_Terminate_Call{Call: _e.mock.On("Terminate", ctx)}
}

func (_c *MouseSourceMock_Terminate_Call) Run(run func(ctx context.Context)) *MouseSourceMock_Terminate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MouseSourceMock_Terminate_Call) Return(err error) *MouseSourceMock_Terminate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MouseSourceMock_Terminate_Call) RunAndReturn(run func(ctx context.Context) error) *MouseSourceMock_Terminate_Call {
	_c.Call.Return(run)
	return _c
}
