// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package peripheral

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMouseSinkMock creates a new instance of MouseSinkMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMouseSinkMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MouseSinkMock {
	mock := &MouseSinkMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MouseSinkMock is an autogenerated mock type for the MouseSink type
type MouseSinkMock struct {
	mock.Mock
}

type MouseSinkMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MouseSinkMock) EXPECT() *MouseSinkMock_Expecter {
	return &MouseSinkMock_Expecter{mock: &_m.Mock}
}

// GetCapabilities provides a mock function for the type MouseSinkMock
func (_mock *MouseSinkMock) GetCapabilities() []PeripheralCapability {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCapabilities")
	}

	var r0 []PeripheralCapability
	if returnFunc, ok := ret.Get(0).(func() []PeripheralCapability); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PeripheralCapability)
		}
	}
	return r0
}

// MouseSinkMock_GetCapabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCapabilities'
type MouseSinkMock_GetCapabilities_Call struct {
	*mock.Call
}

// GetCapabilities is a helper method to define mock.On call
func (_e *MouseSinkMock_Expecter) GetCapabilities() *MouseSinkMock_GetCapabilities_Call {
	return &MouseSinkMock_GetCapabilities_Call{Call: _e.mock.On("GetCapabilities")}
}

func (_c *MouseSinkMock_GetCapabilities_Call) Run(run func()) *MouseSinkMock_GetCapabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MouseSinkMock_GetCapabilities_Call) Return(peripheralCapabilitys []PeripheralCapability) *MouseSinkMock_GetCapabilities_Call {
	_c.Call.Return(peripheralCapabilitys)
	return _c
}

func (_c *MouseSinkMock_GetCapabilities_Call) RunAndReturn(run func() []PeripheralCapability) *MouseSinkMock_GetCapabilities_Call {
	_c.Call.Return(run)
	return _c
}

// GetId provides a mock function for the type MouseSinkMock
func (_mock *MouseSinkMock) GetId() PeripheralId {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetId")
	}

	var r0 PeripheralId
	if returnFunc, ok := ret.Get(0).(func() PeripheralId); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(PeripheralId)
	}
	return r0
}

// MouseSinkMock_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type MouseSinkMock_GetId_Call struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
func (_e *MouseSinkMock_Expecter) GetId() *MouseSinkMock_GetId_Call {
	return &MouseSinkMock_GetId_Call{Call: _e.mock.On("GetId")}
}

func (_c *MouseSinkMock_GetId_Call) Run(run func()) *MouseSinkMock_GetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MouseSinkMock_GetId_Call) Return(peripheralId PeripheralId) *MouseSinkMock_GetId_Call {
	_c.Call.Return(peripheralId)
	return _c
}

func (_c *MouseSinkMock_GetId_Call) RunAndReturn(run func() PeripheralId) *MouseSinkMock_GetId_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MouseSinkMock
func (_mock *MouseSinkMock) GetName() PeripheralName {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 PeripheralName
	if returnFunc, ok := ret.Get(0).(func() PeripheralName); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(PeripheralName)
	}
	return r0
}

// MouseSinkMock_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MouseSinkMock_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MouseSinkMock_Expecter) GetName() *MouseSinkMock_GetName_Call {
	return &MouseSinkMock_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MouseSinkMock_GetName_Call) Run(run func()) *MouseSinkMock_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MouseSinkMock_GetName_Call) Return(peripheralName PeripheralName) *MouseSinkMock_GetName_Call {
	_c.Call.Return(peripheralName)
	return _c
}

func (_c *MouseSinkMock_GetName_Call) RunAndReturn(run func() PeripheralName) *MouseSinkMock_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// Terminate provides a mock function for the type MouseSinkMock
func (_mock *MouseSinkMock) Terminate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Terminate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MouseSinkMock_Terminate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Terminate'
type MouseSinkMock_Terminate_Call struct {
	*mock.Call
}

// Terminate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MouseSinkMock_Expecter) Terminate(ctx interface{}) *MouseSinkMock_Terminate_Call {
	return &MouseSinkMock_Terminate_Call{Call: _e.mock.On("Terminate", ctx)}
}

func (_c *MouseSinkMock_Terminate_Call) Run(run func(ctx context.Context)) *MouseSinkMock_Terminate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MouseSinkMock_Terminate_Call) Return(err error) *MouseSinkMock_Terminate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MouseSinkMock_Terminate_Call) RunAndReturn(run func(ctx context.Context) error) *MouseSinkMock_Terminate_Call {
	_c.Call.Return(run)
	return _c
}
