// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package peripheral

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMouseSourceMock creates a new instance of MouseSourceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMouseSourceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MouseSourceMock {
	mock := &MouseSourceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MouseSourceMock is an autogenerated mock type for the MouseSource type
type MouseSourceMock struct {
	mock.Mock
}

type MouseSourceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MouseSourceMock) EXPECT() *MouseSourceMock_Expecter {
	return &MouseSourceMock_Expecter{mock: &_m.Mock}
}

// Capabilities provides a mock function for the type MouseSourceMock
func (_mock *MouseSourceMock) Capabilities() []PeripheralCapability {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Capabilities")
	}

	var r0 []PeripheralCapability
	if returnFunc, ok := ret.Get(0).(func() []PeripheralCapability); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PeripheralCapability)
		}
	}
	return r0
}

// MouseSourceMock_Capabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capabilities'
type MouseSourceMock_Capabilities_Call struct {
	*mock.Call
}

// Capabilities is a helper method to define mock.On call
func (_e *MouseSourceMock_Expecter) Capabilities() *MouseSourceMock_Capabilities_Call {
	return &MouseSourceMock_Capabilities_Call{Call: _e.mock.On("Capabilities")}
}

func (_c *MouseSourceMock_Capabilities_Call) Run(run func()) *MouseSourceMock_Capabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MouseSourceMock_Capabilities_Call) Return(peripheralCapabilitys []PeripheralCapability) *MouseSourceMock_Capabilities_Call {
	_c.Call.Return(peripheralCapabilitys)
	return _c
}

func (_c *MouseSourceMock_Capabilities_Call) RunAndReturn(run func() []PeripheralCapability) *MouseSourceMock_Capabilities_Call {
	_c.Call.Return(run)
	return _c
}

// Id provides a mock function for the type MouseSourceMock
func (_mock *MouseSourceMock) Id() PeripheralId {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Id")
	}

	var r0 PeripheralId
	if returnFunc, ok := ret.Get(0).(func() PeripheralId); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(PeripheralId)
	}
	return r0
}

// MouseSourceMock_Id_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Id'
type MouseSourceMock_Id_Call struct {
	*mock.Call
}

// Id is a helper method to define mock.On call
func (_e *MouseSourceMock_Expecter) Id() *MouseSourceMock_Id_Call {
	return &MouseSourceMock_Id_Call{Call: _e.mock.On("Id")}
}

func (_c *MouseSourceMock_Id_Call) Run(run func()) *MouseSourceMock_Id_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MouseSourceMock_Id_Call) Return(peripheralId PeripheralId) *MouseSourceMock_Id_Call {
	_c.Call.Return(peripheralId)
	return _c
}

func (_c *MouseSourceMock_Id_Call) RunAndReturn(run func() PeripheralId) *MouseSourceMock_Id_Call {
	_c.Call.Return(run)
	return _c
}

// Terminate provides a mock function for the type MouseSourceMock
func (_mock *MouseSourceMock) Terminate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Terminate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MouseSourceMock_Terminate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Terminate'
type MouseSourceMock_Terminate_Call struct {
	*mock.Call
}

// Terminate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MouseSourceMock_Expecter) Terminate(ctx interface{}) *MouseSourceMock_Terminate_Call {
	return &MouseSourceMock_Terminate_Call{Call: _e.mock.On("Terminate", ctx)}
}

func (_c *MouseSourceMock_Terminate_Call) Run(run func(ctx context.Context)) *MouseSourceMock_Terminate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MouseSourceMock_Terminate_Call) Return(err error) *MouseSourceMock_Terminate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MouseSourceMock_Terminate_Call) RunAndReturn(run func(ctx context.Context) error) *MouseSourceMock_Terminate_Call {
	_c.Call.Return(run)
	return _c
}
