### Connect display sink to display source
POST http://127.0.0.1:8080/router/display/connect
Content-Type: application/json

{
  "displaySource": {
    "machineName": "ffmpeg-display-source",
    "peripheralName": "ffmpeg-display-source"
  },
  "displaySink": {
    "machineName": "ffmpeg-display-sink",
    "peripheralName": "ffmpeg-display-sink"
  }
}
